import React from 'react';
import {
  ShieldCheck,
  Cpu,
  Lock,
  FileCheck2,
  BarChart3,
  Network,
  CheckCircle2,
  AlertTriangle,
  Sparkles,
  Database
} from 'lucide-react';

export default function Principles() {
  const principles = [
    {
      title: 'Deterministic AI vs. LLM Hallucination',
      icon: Cpu,
      color: 'indigo',
      summary: 'Why candidate scoring must be mathematically reproducible, not generated by stochastic prompts.',
      points: [
        'Pure LLM prompts ("Rate this resume 1 to 10") vary across seeds, temperatures, and versions, introducing arbitrary evaluation drift.',
        'IntelliResume uses local dense embeddings (all-MiniLM-L6-v2), a 36-node canonical ontology graph with 125 aliases, and a deterministic linear formulation: Score = ∑ (w_i · s_i).',
        'Every single point in the composite score is traced to an explicit mathematical contribution in the 8-layer breakdown.'
      ]
    },
    {
      title: 'Privacy-First Ephemeral Architecture',
      icon: Lock,
      color: 'emerald',
      summary: 'Candidate data is processed in-memory without persistent document retention.',
      points: [
        'Zero-retention policy: uploaded resumes are processed strictly in RAM during the API request lifecycle; no candidate files are permanently stored on disk.',
        'Automated PII scrubbing: regex-based anonymization for email addresses, phone numbers, and profile URLs.',
        'Blind-screening mode: enables unconscious bias reduction by scrubbing candidate names and personal identifiers prior to scoring.'
      ]
    },
    {
      title: 'Citation-Grounded Evidence Matrix',
      icon: FileCheck2,
      color: 'cyan',
      summary: 'No ungrounded claims: every qualification status is anchored to exact textual citations.',
      points: [
        'Direct matches require exact canonical identification and return the literal quote from the resume.',
        'Transferable matches traverse ontology edges (e.g., Flask → FastAPI at 0.85 transferability) with explicit penalty accounting.',
        'The EvidenceGroundingValidator guarantees that resume improvement suggestions never hallucinate unanchored skills or fabricate unearned metrics.'
      ]
    },
    {
      title: 'Empirical Evaluation & Quality Transparency',
      icon: BarChart3,
      color: 'purple',
      summary: 'Genuine benchmark calculation over curated gold-standard test pairs, not marketing claims.',
      points: [
        '12 curated golden test pairs with 85 human-annotated ground-truth skills and 44 requirement checks.',
        'Genuinely computed metrics: Skill Extraction F1 = 0.929 (Precision 0.941, Recall 0.918), Job Requirement Accuracy = 93.2%, Semantic MRR = 0.750.',
        'Full public failure mode transparency: the system explicitly documents false positives, false negatives, and edge-case limitations in the Evaluation tab.'
      ]
    }
  ];

  return (
    <div className="space-y-8 max-w-6xl mx-auto py-2">
      {/* Header */}
      <div className="space-y-2 pb-6 border-b border-white/10">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400">
            <ShieldCheck className="w-4 h-4" />
          </div>
          <h1 className="text-2xl font-extrabold text-white tracking-tight">
            Engineering Principles &amp; AI Safety
          </h1>
        </div>
        <p className="text-xs text-slate-400 max-w-2xl leading-relaxed">
          Architectural philosophy and engineering standards governing IntelliResume AI: deterministic mathematical reproducibility, zero-retention privacy, citation-grounded evidence, and honest empirical benchmarks.
        </p>
      </div>

      {/* Comparison Grid: Probabilistic LLM vs IntelliResume Architecture */}
      <div className="glass-card rounded-2xl p-6 border border-white/10 space-y-4">
        <h3 className="text-sm font-bold text-white flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-indigo-400" />
          <span>Architectural Comparison: Pure LLM Prompts vs. Deterministic AI Pipeline</span>
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
          {/* Pure LLM / GenAI */}
          <div className="p-4 rounded-xl bg-rose-500/[0.03] border border-rose-500/20 space-y-3">
            <div className="flex items-center gap-2 text-rose-400 font-semibold font-mono text-[11px]">
              <AlertTriangle className="w-4 h-4" />
              <span>TRADITIONAL GEN-AI / PURE LLM APPROACH</span>
            </div>
            <ul className="space-y-2 text-slate-400 text-[11px] leading-relaxed">
              <li className="flex items-start gap-2">
                <span className="text-rose-400 font-bold">•</span>
                <span><b>Stochastic Variability:</b> Same candidate evaluated twice produces different match scores.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-rose-400 font-bold">•</span>
                <span><b>Opaque Black-Box:</b> Inability to mathematically audit why a candidate was ranked above another.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-rose-400 font-bold">•</span>
                <span><b>Hallucination Vulnerability:</b> Fabricates unearned achievements, unlisted skills, or unrealistic percentages.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-rose-400 font-bold">•</span>
                <span><b>API Latency &amp; Cost:</b> Expensive cloud API calls with unpredictable rate limits and latency spikes.</span>
              </li>
            </ul>
          </div>

          {/* IntelliResume Deterministic Pipeline */}
          <div className="p-4 rounded-xl bg-emerald-500/[0.03] border border-emerald-500/20 space-y-3">
            <div className="flex items-center gap-2 text-emerald-400 font-semibold font-mono text-[11px]">
              <CheckCircle2 className="w-4 h-4" />
              <span>INTELLIRESUME DETERMINISTIC AI ENGINE</span>
            </div>
            <ul className="space-y-2 text-slate-300 text-[11px] leading-relaxed">
              <li className="flex items-start gap-2">
                <span className="text-emerald-400 font-bold">•</span>
                <span><b>100% Deterministic:</b> Identical input vectors and profiles produce identical scores every run.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-emerald-400 font-bold">•</span>
                <span><b>Explainable Linear Math:</b> Score = ∑ (w_i · s_i) with dynamic redistribution and exact contribution percentages.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-emerald-400 font-bold">•</span>
                <span><b>Evidence Grounded:</b> Every qualification status links directly to verbatim candidate citations.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-emerald-400 font-bold">•</span>
                <span><b>Local CPU Embedding:</b> Runs sentence-transformers locally with ~40ms average inference latency.</span>
              </li>
            </ul>
          </div>
        </div>
      </div>

      {/* 4 Pillars Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {principles.map((p, idx) => {
          const Icon = p.icon;
          return (
            <div key={idx} className="glass-card rounded-2xl p-6 border border-white/5 space-y-4 flex flex-col justify-between">
              <div className="space-y-3">
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400">
                    <Icon className="w-4 h-4" />
                  </div>
                  <div>
                    <h3 className="text-sm font-bold text-white">{p.title}</h3>
                    <p className="text-[11px] text-slate-400">{p.summary}</p>
                  </div>
                </div>

                <div className="pt-2 space-y-2">
                  {p.points.map((pt, pIdx) => (
                    <div key={pIdx} className="flex items-start gap-2 text-xs text-slate-300 leading-relaxed">
                      <span className="text-indigo-400 font-mono mt-0.5 font-bold">›</span>
                      <span>{pt}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Technical Stack Architecture Footnote */}
      <div className="glass-card rounded-2xl p-6 border border-white/5 bg-[#0B0F19] flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-slate-400">
        <div className="space-y-1">
          <div className="text-white font-semibold">Production Cloud Infrastructure</div>
          <div>Frontend: React 18 + Vite on Vercel • Backend: Python 3.11 + FastAPI on Render</div>
        </div>
        <div className="flex items-center gap-3 font-mono text-[11px] text-slate-400">
          <span className="px-2.5 py-1 rounded bg-white/5 border border-white/10 text-slate-300">PyTorch CPU</span>
          <span className="px-2.5 py-1 rounded bg-white/5 border border-white/10 text-slate-300">all-MiniLM-L6-v2</span>
          <span className="px-2.5 py-1 rounded bg-white/5 border border-white/10 text-slate-300">FastAPI REST</span>
        </div>
      </div>
    </div>
  );
}
